spring:
  application:
    name: event-service
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    hostname: ${EUREKA_EVENT_HOSTNAME:localhost}
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  circuitbreaker:
    enabled: true
resilience4j.circuitbreaker:
  instances:
    user-service:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 5s
      minimumNumberOfCalls: 5
      recordExceptions:
        - feign.FeignException
        - java.net.ConnectException
        - java.net.SocketTimeoutException
logging:
  level:
    org.springframework.cloud.circuitbreaker.resilience4j: DEBUG